
services:
  generate_dialogue_cn:
    image: rct-docker-registry.cn-zhangjiakou.cr.aliyuncs.com/algorithm/generatedialogue-cn:v0
    container_name: xianjian_generate_dialogue
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    working_dir: "/workspace"
    command: ['python', 'app.py', '--model_dir=runs/Sep03_11-46-25_node3']
    ports:
      - 8088:8088

    restart: always
    volumes:
      - $PWD/../:/workspace

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]

